server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-serie
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  data:
    mongodb:
      username: usr-series-mongo
      password: pwd-series-mongo
      database: series-dev-mongo
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

info:
  app:
    name: serie-service
    description: Series
    version: 1.0.0
